on:
  push:
    branches:
      - develop
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create screenshots folder
        run: mkdir -p .github/screenshots
      - run: pwd
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://birthday-countdown.vercel.app/?b=2022-11-29
          destination: .github/screenshots/web_screenshot.png

      - run: ls -lh .github/screenshots
